### ISSUE TITLE
Add command to quickly create and draft a new post

### ISSUE THREAD

**Issue by mjm** [mjm/pressy#21]
Currently the workflow for making a new post is a little clumsy:

1. `vi <format>/some-dummy-name.md`
2. Enter some frontmatter, especially to set the status to publish for quick tweet-like posts that don't need to be drafts
3. Draft the text of the post
4. `pressy push`

There's a lot of room for improvement here. I think being able to work in this flow as described is a goal of Pressy, but only for longer form writing. It's needlessly tedious for shorter content.

What I'm imagining is something like `pressy write` that creates a file in the right place, with a placeholder name, and possibly fills in some frontmatter ahead of time. Some options to the command would control this. It would then use `$EDITOR` to open the file it created, popping you straight into the editor, ready to go. When leaving the editor, it could rename the file based on the content.

It's an open question as to whether this may also go ahead and do a push, or maybe just create the specific post, or do nothing.

**Comment by mjm** [comment]
I've got a spike locally that does this, and it works pretty well. I need to figure out how to factor this out into easily testable API.

**Comment by mjm** [comment]
## Tasks

- [ ] Create empty post template maker
- [ ] Create post editor
  - Consumes and produces `Pressy::Post`, rendered version is internal
- [ ] Add `Site` method to create a single post
